# this is possibly the dumbest makefile ever, but it at least saves you from typing the commands out...
default:
	g++ generate.cpp -o generate -std=c++11 -O2
debug:
	g++ generate.cpp -o generate -std=c++11 -g